/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package blood;

/**
 *
 * @author MANU
 */
public class MAINPAGE extends javax.swing.JFrame {

    /**
     * Creates new form MAINPAGE
     */
    public MAINPAGE() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabelblood = new javax.swing.JLabel();
        jLabelbank = new javax.swing.JLabel();
        jLabeldonor = new javax.swing.JLabel();
        jLabelclose = new javax.swing.JLabel();
        jLabelmin = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        jPanel1.setLayout(null);

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 48)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("BLOOD DONATION");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(350, 90, 550, 70);

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 48)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("MANAGEMENT");
        jPanel1.add(jLabel3);
        jLabel3.setBounds(410, 180, 360, 58);

        jLabelblood.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabelblood.setForeground(new java.awt.Color(255, 255, 255));
        jLabelblood.setText("Blood records");
        jLabelblood.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelbloodMouseClicked(evt);
            }
        });
        jPanel1.add(jLabelblood);
        jLabelblood.setBounds(380, 650, 250, 60);

        jLabelbank.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabelbank.setForeground(new java.awt.Color(255, 255, 255));
        jLabelbank.setText("Blood bank records");
        jLabelbank.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelbankMouseClicked(evt);
            }
        });
        jPanel1.add(jLabelbank);
        jLabelbank.setBounds(700, 510, 360, 60);

        jLabeldonor.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabeldonor.setForeground(new java.awt.Color(255, 255, 255));
        jLabeldonor.setText("Donor details");
        jLabeldonor.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabeldonorMouseClicked(evt);
            }
        });
        jPanel1.add(jLabeldonor);
        jLabeldonor.setBounds(10, 510, 250, 60);

        jLabelclose.setFont(new java.awt.Font("Tahoma", 1, 48)); // NOI18N
        jLabelclose.setForeground(new java.awt.Color(255, 255, 255));
        jLabelclose.setText("x");
        jLabelclose.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelcloseMouseClicked(evt);
            }
        });
        jPanel1.add(jLabelclose);
        jLabelclose.setBounds(1020, 0, 40, 50);

        jLabelmin.setFont(new java.awt.Font("Tahoma", 1, 48)); // NOI18N
        jLabelmin.setForeground(new java.awt.Color(255, 255, 255));
        jLabelmin.setText("-");
        jLabelmin.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelminMouseClicked(evt);
            }
        });
        jPanel1.add(jLabelmin);
        jLabelmin.setBounds(990, 10, 30, 30);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 48)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setIcon(new javax.swing.ImageIcon("C:\\Users\\MANU\\Documents\\NetBeansProjects\\BLOOD\\src\\blood\\Download Wallpaper blood drops wave HD Background.jpg")); // NOI18N
        jPanel1.add(jLabel1);
        jLabel1.setBounds(-30, -30, 1210, 850);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 1063, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 740, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jLabelcloseMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelcloseMouseClicked
        System.exit(0);
        // TODO add your handling code here:
    }//GEN-LAST:event_jLabelcloseMouseClicked

    private void jLabelminMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelminMouseClicked
        this.setState(JFrame.ICONIFIED);        // TODO add your handling code here:
    }//GEN-LAST:event_jLabelminMouseClicked

    private void jLabeldonorMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabeldonorMouseClicked
        // TODO add your handling code here:
       DONORDETAILS DD=new  DONORDETAILS();
        DD.setVisible(true);
        DD.pack();
        DD.setLocationRelativeTo(null);
        DD.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        this.dispose();
        
    }//GEN-LAST:event_jLabeldonorMouseClicked

    private void jLabelbloodMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelbloodMouseClicked
        // TODO add your handling code here:
        blooddetails b=new  blooddetails();
        b.setVisible(true);
        b.pack();
        b.setLocationRelativeTo(null);
        b.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        this.dispose();
    }//GEN-LAST:event_jLabelbloodMouseClicked

    private void jLabelbankMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelbankMouseClicked
        // TODO add your handling code here:
         bloodbankdetails bb=new  bloodbankdetails();
        bb.setVisible(true);
        bb.pack();
        bb.setLocationRelativeTo(null);
        bb.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        this.dispose();
    }//GEN-LAST:event_jLabelbankMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MAINPAGE.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MAINPAGE.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MAINPAGE.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MAINPAGE.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MAINPAGE().setVisible(true);
            }
        });
    }
private javax.swing.JFrame JFrame;
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabelbank;
    private javax.swing.JLabel jLabelblood;
    private javax.swing.JLabel jLabelclose;
    private javax.swing.JLabel jLabeldonor;
    private javax.swing.JLabel jLabelmin;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
